# Generated by Django 5.2.2 on 2025-06-30 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_alter_appointment_patient"),
        ("users", "0004_alter_patientprofile_address_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="appointment",
            name="unique_date_patient_doctor",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.patientprofile"
            ),
        ),
    ]
