# Generated by Django 5.2.2 on 2025-07-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0005_remove_appointment_unique_date_patient_doctor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
