# Generated by Django 5.2.2 on 2025-07-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0006_appointment_paid"),
        ("users", "0006_alter_doctorprofile_image"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="appointment",
            name="unique_date_time",
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                fields=("appointment_date", "appointment_time", "state"),
                name="unique_date_time",
            ),
        ),
    ]
