# Generated by Django 5.2.2 on 2025-07-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0007_remove_appointment_unique_date_time_and_more"),
        ("users", "0006_alter_doctorprofile_image"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="appointment",
            name="unique_date_time",
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "cancelled"), _negated=True),
                fields=("appointment_date", "appointment_time"),
                name="unique_date_time",
            ),
        ),
    ]
