# Generated by Django 5.2.2 on 2025-07-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0008_remove_appointment_unique_date_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="reserved_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("scheduled", "Scheduled"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
