# Generated by Django 5.2.2 on 2025-06-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='image',
            field=models.ImageField(null=True, upload_to='doctor_images'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='image',
            field=models.ImageField(null=True, upload_to='pateint_images'),
        ),
    ]
