# Generated by Django 5.2.2 on 2025-06-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='address',
            new_name='address_line1',
        ),
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='specialization',
            new_name='speciality',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='address_line2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
