# Generated by Django 5.2.2 on 2025-07-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_rename_address_patientprofile_address_line1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorprofile",
            name="image",
            field=models.ImageField(
                default="defaults/upload_area.png", upload_to="doctor_images"
            ),
        ),
    ]
