# Generated by Django 5.2.2 on 2025-07-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_doctorprofile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorprofile",
            name="image",
            field=models.ImageField(
                default="https://res.cloudinary.com/dsccsqdk2/image/upload/v1751626552/profile_icon_dggge8.png",
                max_length=500,
                upload_to="doctor_images",
            ),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="image",
            field=models.ImageField(
                default="https://res.cloudinary.com/dsccsqdk2/image/upload/v1751626552/profile_icon_dggge8.png",
                max_length=500,
                null=True,
                upload_to="pateint_images",
            ),
        ),
    ]
